# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "58928b5d71d8f97ebd905e289c151269"
name = "Sherpa"
handle = "sherpa-chatbot-production"
application_url = "https://sherpa-prod-8bafaab678a7.herokuapp.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dummy-store-usa.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_discounts,write_order_edits,write_orders"

[auth]
redirect_urls = [
  "https://sherpa-prod-8bafaab678a7.herokuapp.com/auth/callback",
  "https://sherpa-prod-8bafaab678a7.herokuapp.com/auth/shopify/callback",
  "https://sherpa-prod-8bafaab678a7.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2023-04"

  [[webhooks.subscriptions]]
  uri = "https://us-central1-sherpa-dc1fe.cloudfunctions.net/gdpr/customer/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://us-central1-sherpa-dc1fe.cloudfunctions.net/gdpr/customer/request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://us-central1-sherpa-dc1fe.cloudfunctions.net/gdpr/store/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/billing"

[pos]
embedded = false
